_target_: uni2ts.data.builder.ConcatDatasetBuilder
_args_:
  _target_: uni2ts.data.builder.simple.generate_eval_builders
  dataset: ECL_finetune_eval
  offset: 2600
  eval_length: 2000
  prediction_lengths: [24, 48, 96]
  context_lengths: [512]
  patch_sizes: [32]