_target_: uni2ts.model.moirai.MoiraiForecast
module:
  _target_: uni2ts.model.moirai.MoiraiModule.from_pretrained
  pretrained_model_name_or_path: model/moirai-1.0-R-large
num_samples: 5
patch_size: ???
context_length: ???