_target_: uni2ts.model.moirai.MoiraiForecast.load_from_checkpoint
checkpoint_path: outputs/finetune/moirai_1.0_R_large/ecl/ecl_finetune/checkpoints/epoch=3-step=400.ckpt
num_samples: 100
patch_size: ???
context_length: ???
